In [1]:
import numpy as np

import random

In [7]:
A = np.random.rand(8, 1)
Y = np.zeros((8, 1))

In [8]:
A

array([[ 0.18166161],
       [ 0.48287205],
       [ 0.66137827],
       [ 0.02926296],
       [ 0.17670904],
       [ 0.34404886],
       [ 0.68231714],
       [ 0.36533218]])

In [19]:
Y = np.where(A < 0.5, 0, 1)
Y

array([[0],
       [0],
       [1],
       [0],
       [0],
       [0],
       [1],
       [0]])

In [9]:
np.where?

In [2]:
a = np.random.rand(5)

In [3]:
type(a)

numpy.ndarray

In [4]:
a.shape

(5,)

In [5]:
a_ = np.random.rand(5, 1)

In [6]:
a_

array([[ 0.28911663],
       [ 0.27061558],
       [ 0.25851655],
       [ 0.44791091],
       [ 0.21491126]])

In [7]:
type(a_)

numpy.ndarray

In [8]:
a_.shape

(5, 1)

In [11]:
np.linalg.norm?

In [12]:
np.zeros((4, 1))

array([[ 0.],
       [ 0.],
       [ 0.],
       [ 0.]])

In [13]:
cost = np.array([4])
cost.shape

(1,)

In [16]:
np.squeeze?

In [ ]:
A = np.array([])